export default {
  PAYMENT_REQUEST_ACCEPTED: "PAYMENT_REQUEST_ACCEPTED",
  QUOTATION_RECEIVED: "QUOTATION_RECEIVED",
  EXECUTION_RECEIVED: "EXECUTION_RECEIVED",
  TRANSACTION_INITIATED: "TRANSACTION_INITIATED",
  TRANSACTION_RECEIVED: "TRANSACTION_RECEIVED",
  TRANSACTION_CONFIRMED: "TRANSACTION_CONFIRMED",
};
